/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\tutorial\MINIMAL.cbl */
/* Generated at           nov 24 2022 22:00:52 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -x -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\tutorial\CopyBooks -IC:\desenv\COBOL\tutorial\CopyBooks\Public -tMINIMAL.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\tutorial\MINIMAL.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"nov 24 2022 22:00:52"
#define  COB_MODULE_DATE		20221124
#define  COB_MODULE_TIME		220052

/* Global variables */
#include "MINIMAL.c.h"

/* Function prototypes */

static int		MINIMAL ();
static int		MINIMAL_ (const int);
static void		MINIMAL_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MINIMAL ());
}

/* Functions */

/* PROGRAM-ID 'MINIMAL' */

/* ENTRY 'MINIMAL' */

static int
MINIMAL ()
{
  return MINIMAL_ (0);
}

static int
MINIMAL_ (const int entry)
{
  /* Program local variables */
  #include "MINIMAL.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 12        : Entry     MINIMAL                 : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  l_2:;
#line 12 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  ENTRY_MINIMAL:;
#line 100 "MINIMAL.c"
#line 13 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  SECTION_MAIN_20SECTION:;
#line 103 "MINIMAL.c"
#line 13 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_nop ();
#line 106 "MINIMAL.c"

  /* Line: 13        : DISPLAY            : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x0010000D;
#line 13 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 112 "MINIMAL.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 14        : MOVE               : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x0010000E;
#line 14 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_2);
#line 119 "MINIMAL.c"
  cob_setswp_s16 (b_8, 10);

  /* Line: 16        : MOVE               : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x00100010;
#line 16 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_2);
#line 126 "MINIMAL.c"
  memset (b_8 + 2, 32, 10);

  /* Line: 17        : MOVE               : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x00100011;
#line 17 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_2);
#line 133 "MINIMAL.c"
  memcpy (b_8 + 2, "WESLEY", 6);

  /* Line: 18        : MOVE               : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x00100012;
#line 18 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_2);
#line 140 "MINIMAL.c"
  memcpy (b_8 + 9, "MR.", 3);

  /* Line: 19        : CALL               : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x00100013;
#line 19 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_3);
#line 147 "MINIMAL.c"
  cob_procedure_params[0] = &f_8;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_SRMINIMAL.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_SRMINIMAL.funcvoid = cob_resolve_cobol ("SRMINIMAL", 0, 1);
  }
  b_2 = ((int (*)(void *))call_SRMINIMAL.funcint) (b_8);

  /* Line: 20        : DISPLAY            : c:\desenv\COBOL\tutorial\MINIMAL.cbl */
  module->module_stmt = 0x00100014;
#line 20 "c:\\desenv\\COBOL\\tutorial\\MINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 162 "MINIMAL.c"
  cob_display (0, 1, 1, &c_2);

  module->module_stmt = 0x00100015;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MINIMAL_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memset (b_8, 0, 2);
  memset (b_8 + 2, 32, 10);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MINIMAL' */

/* Initialize module structure for MINIMAL */
static void MINIMAL_module_init (cob_module *module)
{
  module->module_name = "MINIMAL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())MINIMAL;
  module->module_cancel.funcptr = (void *(*)())MINIMAL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

