/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
/* Generated at           nov 24 2022 21:47:22 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -o SRMINIMAL.dll -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\tutorial\CopyBooks -IC:\desenv\COBOL\tutorial\CopyBooks\Public -tSRMINIMAL.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */

static cob_u8_t			*cob_parm_8 = NULL;

/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   4,   0, 0x0021, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {22, (cob_u8_ptr)"SRMINIMAL.cbl - INICIO", &a_1};
static const cob_field c_2	= {9, (cob_u8_ptr)"TAMANHO: ", &a_1};
static const cob_field c_3	= {9, (cob_u8_ptr)"TEXTO  : ", &a_1};
static const cob_field c_4	= {19, (cob_u8_ptr)"SRMINIMAL.cbl - FIM", &a_1};


/* Strings */
static const char st_1[]	= "DISPLAY";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"};
