/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
/* Generated at           nov 24 2022 21:47:22 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -o SRMINIMAL.dll -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\tutorial\CopyBooks -IC:\desenv\COBOL\tutorial\CopyBooks\Public -tSRMINIMAL.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"nov 24 2022 21:47:22"
#define  COB_MODULE_DATE		20221124
#define  COB_MODULE_TIME		214722

/* Global variables */
#include "SRMINIMAL.c.h"

/* Function prototypes */

__declspec(dllexport) int		SRMINIMAL (cob_u8_t *);
static int		SRMINIMAL_ (const int, cob_u8_t *);
static void		SRMINIMAL_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'SRMINIMAL' */

/* ENTRY 'SRMINIMAL' */

int
SRMINIMAL (cob_u8_t *b_8)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 1;
  };

  /* Set the parameter list */
  switch (cob_call_params) {
  case 0:
  	break;
  default:
  	cob_parm_8 = b_8;
  	break;
}
  return SRMINIMAL_ (0, cob_parm_8);
}

static int
SRMINIMAL_ (const int entry, cob_u8_t *b_8)
{
  /* Program local variables */
  #include "SRMINIMAL.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_8 = b_8;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 9         : Entry     SRMINIMAL               : c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
  l_2:;
#line 9 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  ENTRY_SRMINIMAL:;
#line 111 "SRMINIMAL.c"
#line 10 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  SECTION_MAIN_20SECTION:;
#line 114 "SRMINIMAL.c"
#line 10 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  cob_nop ();
#line 117 "SRMINIMAL.c"

  /* Line: 10        : DISPLAY            : c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
  module->module_stmt = 0x0010000A;
#line 10 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 123 "SRMINIMAL.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 11        : DISPLAY            : c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
  module->module_stmt = 0x0010000B;
#line 11 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 130 "SRMINIMAL.c"
  cob_display (0, 1, 2, &c_2, COB_SET_DATA (f_9, b_8));

  /* Line: 12        : DISPLAY            : c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
  module->module_stmt = 0x0010000C;
#line 12 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 137 "SRMINIMAL.c"
  cob_display (0, 1, 2, &c_3, COB_SET_DATA (f_10, b_8 + 2));

  /* Line: 13        : DISPLAY            : c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
  module->module_stmt = 0x0010000D;
#line 13 "c:\\desenv\\COBOL\\tutorial\\SRMINIMAL.cbl"
  cob_trace_stmt (st_1);
#line 144 "SRMINIMAL.c"
  cob_display (0, 1, 1, &c_4);

  module->module_stmt = 0x0010000F;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  SRMINIMAL_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  cob_parm_8 = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'SRMINIMAL' */

/* Initialize module structure for SRMINIMAL */
static void SRMINIMAL_module_init (cob_module *module)
{
  module->module_name = "SRMINIMAL";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())SRMINIMAL;
  module->module_cancel.funcptr = (void *(*)())SRMINIMAL_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

