/* Generated by           cobc 3.1.2.0 */
/* Generated from         c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */
/* Generated at           nov 24 2022 21:47:22 */
/* GnuCOBOL build date    Aug 31 2022 20:58:34 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        c:\gc312vbi\bin\cobc -o SRMINIMAL.dll -std=ibm -Wall -I$(workspaceFolder} -IC:\desenv\COBOL\tutorial\CopyBooks -IC:\desenv\COBOL\tutorial\CopyBooks\Public -tSRMINIMAL.LST -v -g -Xref -ftsymbols c:\desenv\COBOL\tutorial\SRMINIMAL.cbl */

/* Program local variables for 'SRMINIMAL' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_8;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_9	= {2, NULL, &a_2};	/* WK-PARM-LEN */
static cob_field f_10	= {10, NULL, &a_3};	/* WK-PARM-TXT */

/* End of fields */

